services:
  viami_api:
    container_name: viami_api
    image: node:lts
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./src/.env
    working_dir: /home/viami/app
    volumes:
      - ./src/api:/home/viami/app/src/api
    command: > 
      bash -c 
        'npm i &&
         npm run watch'
    ports:
      - 3333:3000
    depends_on:
      - viami_db
    links:
      - viami_db
    networks:
      - viami_back

  viami_adminer:
    container_name: viami_adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - viami_db
    networks:
      - viami_back
      
  viami_db:
    container_name: viami_db
    image: mariadb:latest
    env_file: ./src/.env
    volumes:
      - db:/var/lib/mysql
      - ./src/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - viami_back

  viami_test:
    container_name: viami_test
    image: node:lts
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./src/.env
    working_dir: /home/viami/app
    volumes:
      - ./src/api:/home/viami/app/src/api
      - ./tests:/home/viami/app/tests
    command: > 
      bash -c 
        'npm i &&
         npm test'
    networks:
      - viami_back

volumes:
  db:

networks:
  viami_back:
    driver: bridge
