# User official image of Node.js
FROM node:lts

# Define the environment as development
ENV NODE_ENV=development

# Set the user as root
USER root

# Use the repository /app
WORKDIR /app

# Create a non-root user
RUN groupadd -r app && useradd -r -g app -s /bin/false app

# Change ownership of the /app directory to the non-root user
RUN chown -R app:app /app

# Copy the package file to the project
COPY ["package.json", "package-lock.json", "./"]

# Install all the dependencies needed
RUN npm ci --only=production

# Install nodemon package so that the project can run using the command run watch
RUN npm install -g nodemon

# Copy the source code
COPY . .

# Expose the port 3000 for the application
EXPOSE 3000

# Switch to the non-root user
USER app

# Run and watch the project
CMD ["npm", "run", "watch"]
